### ISSUE TITLE
FeedTestCase and RSSTestCases are borked

### ISSUE THREAD

**Issue by lucialu94** [CombustibleLemons/rss-reader#95] opened 2014-12-01 21:32 UTC
I am scared to touch the Feed/RSS code without further info, but apparently there's a KeyError on appending things by href?

**Comment by jharriman** [comment] 2014-12-01 21:33
That's what version control is for? ;) I'm not sure what the problem is, but I can take a look sometime.

**Comment by jharriman** [comment] 2014-12-07 19:34
We fixed this? I think we fixed this. Closing.

**Closed as completed by jharriman** 2014-12-07 19:34 UTC
Labels: help wanted
